#!/bin/bash
mysql -u admin -pTeamlaban! -h upoudb1.chioee9qrhwf.us-east-1.rds.amazonaws.com <<EOF
DROP DATABASE IF EXISTS carrental;
CREATE SCHEMA carrental ;
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

CREATE TABLE carrental.cars (
  Id int(11) NOT NULL,
  name varchar(255) NOT NULL,
  code_name varchar(50) NOT NULL,
  model varchar(20) NOT NULL,
  manufacturer varchar(20) NOT NULL,
  year int(4) NOT NULL,
  plate_number varchar(10) NOT NULL,
  RentPerDay double(18,2) NOT NULL,
  Capacity int(2) NOT NULL,
  file_name varchar(255) NOT NULL,
  Is_Active bit(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO carrental.cars (Id, name, code_name, model, manufacturer, year, plate_number, RentPerDay, Capacity, file_name, Is_Active) VALUES
(40, 'Toyota Grandia', 'Toyota Grandia Radiant', 'Grandia', 'Toyota', 1990, 'TBS-7634', 5000.00, 4, '1586654715-Capture.PNG', b'1'),
(49, 'Hyundai Tucson (Yellow)', 'Radiant Hyundai', 'Tucson', 'Hyundai', 1990, 'XTR-3425', 4800.00, 4, 'v1starex1.jpg', b'1'),
(50, 'BMW M3 (Silver)', 'BMW M3 Radiant', 'M3', 'BMW', 1990, 'TRX-0987', 10000.00, 7, '1586954874-.jpg', b'1'),
(51, 'BMW Z4 (Silver)', 'BMW Z4 Radiant', 'Z4', 'BMW', 1990, 'TBS-7764', 20000.00, 2, '1586955163-Capture.PNG', b'1');

CREATE TABLE carrental.clientbookings (
  BookingId int(11) NOT NULL,
  clientId int(11) NOT NULL,
  carId int(11) NOT NULL,
  reference_number varchar(25) NOT NULL,
  start_date date NOT NULL,
  pick_up_datetime datetime NOT NULL,
  number_of_days int(2) NOT NULL,
  add_driver bit(1) DEFAULT NULL,
  driver_name varchar(255) DEFAULT NULL,
  driver_fee_current decimal(10,0) NOT NULL,
  rental_fee_current decimal(10,0) NOT NULL,
  rental_discount decimal(10,0) DEFAULT NULL,
  end_date date NOT NULL,
  return_datetime datetime NOT NULL,
  created_by int(11) NOT NULL,
  updated_by int(11) NOT NULL,
  created_date datetime NOT NULL DEFAULT current_timestamp(),
  updated_date datetime NOT NULL,
  statusId int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO carrental.clientbookings (BookingId, clientId, carId, reference_number, start_date, pick_up_datetime, number_of_days, add_driver, driver_name, driver_fee_current, rental_fee_current, rental_discount, end_date, return_datetime, created_by, updated_by, created_date, updated_date, statusId) VALUES
(34, 97, 40, 'VRS-20041BQ2T', '2020-04-21', '0000-00-00 00:00:00', 2, b'1', '', '1000', '5000', '0', '2020-04-23', '0000-00-00 00:00:00', 12, 0, '2020-04-21 20:44:31', '0000-00-00 00:00:00', 1),
(35, 99, 49, 'VRS-2004CMLZG', '2020-04-21', '0000-00-00 00:00:00', 1, b'1', 'Jan Hope', '1000', '4800', '50', '2020-04-22', '0000-00-00 00:00:00', 12, 0, '2020-04-21 21:11:30', '0000-00-00 00:00:00', 1),
(36, 100, 50, 'VRS-2004EOG26', '2020-04-21', '0000-00-00 00:00:00', 1, b'1', '', '1000', '10000', '200', '2020-04-22', '0000-00-00 00:00:00', 12, 0, '2020-04-21 21:16:47', '0000-00-00 00:00:00', 1),
(37, 99, 51, 'VRS-2004W795F', '2020-04-21', '0000-00-00 00:00:00', 2, b'1', '', '1000', '20000', '0', '2020-04-23', '0000-00-00 00:00:00', 12, 0, '2020-04-21 21:18:30', '0000-00-00 00:00:00', 1),
(38, 99, 49, 'VRS-2004SETNI', '2020-04-23', '0000-00-00 00:00:00', 2, b'1', 'Jan Hope', '1000', '4800', '500', '2020-04-25', '0000-00-00 00:00:00', 12, 0, '2020-04-21 22:32:27', '0000-00-00 00:00:00', 1),
(39, 98, 50, 'VRS-2004ZRQGQ', '2020-04-23', '0000-00-00 00:00:00', 1, b'0', '', '1000', '10000', '0', '2020-04-24', '0000-00-00 00:00:00', 12, 0, '2020-04-21 22:38:49', '0000-00-00 00:00:00', 1),
(40, 97, 40, 'VRS-20047VXT8', '2020-04-24', '0000-00-00 00:00:00', 1, b'0', '', '1000', '5000', '0', '2020-04-25', '0000-00-00 00:00:00', 12, 0, '2020-04-21 22:41:17', '0000-00-00 00:00:00', 1);

CREATE TABLE carrental.clientbookingslogs (
  Id int(11) NOT NULL,
  clientbookings_id int(11) NOT NULL,
  remarks text DEFAULT NULL,
  created_date timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  created_by int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO carrental.clientbookingslogs (Id, clientbookings_id, remarks, created_date, created_by) VALUES
(3, 34, NULL, '2020-04-21 12:44:32', 12),
(4, 35, NULL, '2020-04-21 13:11:30', 12),
(5, 36, NULL, '2020-04-21 13:16:47', 12),
(6, 37, 'client paid 500 for reservation', '2020-04-21 13:18:30', 12),
(7, 38, 'Created this booking', '2020-04-21 14:32:28', 12),
(8, 38, 'client paid 1,000 for this reservation. Please see attached file', '2020-04-21 14:32:28', 12),
(9, 39, 'Created this booking', '2020-04-21 14:38:49', 12),
(10, 39, '', '2020-04-21 14:38:49', 12),
(11, 40, 'Created this booking', '2020-04-21 14:41:17', 12);

CREATE TABLE carrental.clientbookingsphotos (
  Id int(11) NOT NULL,
  booking_id int(11) NOT NULL,
  file_name varchar(255) NOT NULL,
  created_date datetime NOT NULL DEFAULT current_timestamp(),
  Is_Active bit(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO carrental.clientbookingsphotos (Id, booking_id, file_name, created_date, Is_Active) VALUES
(20, 34, '1587473071-CHARM.PNG', '2020-04-21 20:44:31', b'1'),
(21, 35, '1587474690-ESCS_SCMC.PNG', '2020-04-21 21:11:30', b'1'),
(22, 38, '1587479547-CHARM.PNG', '2020-04-21 22:32:27', b'1');

CREATE TABLE carrental.clients (
  Id int(11) NOT NULL,
  name varchar(100) NOT NULL,
  email_address varchar(100) NOT NULL,
  contact_number varchar(100) NOT NULL,
  address varchar(255) NOT NULL,
  government_id_1_path varchar(255) NOT NULL,
  government_id_2_path varchar(255) NOT NULL,
  attachment_1_path varchar(255) NOT NULL,
  attachment_2_path varchar(255) NOT NULL,
  created_date datetime NOT NULL DEFAULT current_timestamp(),
  updated_date date NOT NULL,
  Is_Active bit(1) NOT NULL DEFAULT b'1'
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO carrental.clients (Id, name, email_address, contact_number, address, government_id_1_path, government_id_2_path, attachment_1_path, attachment_2_path, created_date, updated_date, Is_Active) VALUES
(97, 'Jeffry Manhulad', 'jcmanhulad@up.edu.ph', '09268406884', 'Musuan, Dologon, Maramag, Bukidnon', '', '', '', '', '2020-04-13 10:00:47', '0000-00-00', b'1'),
(98, 'asdsa', 'jbbatedio@up.edu.ph', 'asdsa', 'sadsa', '', '', '', '', '2020-04-13 12:26:00', '0000-00-00', b'1'),
(99, 'Jym Bartolaba Batedio', 'jbbatedio@up.edu.ph', '091231231231', 'Barra Opol Misamis Oriental', '', '', '', '', '2020-04-13 13:24:10', '0000-00-00', b'1'),
(100, 'Mary Jeziel Cavan', 'johndue@gmail.com', '34324242', 'Musuan', '', '', '', '', '2020-04-13 21:54:53', '0000-00-00', b'1'),
(101, 'MJ Cavan', 'admin@webdamn.com', '34534534', 'Address', '', '', '', '', '2020-04-15 19:13:12', '0000-00-00', b'1');

CREATE TABLE carrental.clientsphotos (
  Id int(11) NOT NULL,
  client_id int(11) NOT NULL,
  file_name varchar(255) NOT NULL,
  created_date datetime NOT NULL DEFAULT current_timestamp(),
  Is_Active bit(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO carrental.clientsphotos (Id, client_id, file_name, created_date, Is_Active) VALUES
(73, 97, '1586743247-Capture.PNG', '2020-04-13 10:00:47', b'1'),
(75, 99, '1586755450-pngtree-happy-birthday-background-of-stereo-creative-image_104875.jpg', '2020-04-13 13:24:10', b'1'),
(76, 99, '1586755450-smoke-spreading-blue-background_23-2147785936.jpg', '2020-04-13 13:24:10', b'1'),
(77, 99, '1586755450-unnamed.jpg', '2020-04-13 13:24:10', b'1'),
(78, 100, '1586786092-MVIMG_20191117_163234.jpg', '2020-04-13 21:54:53', b'1'),
(79, 100, '1586786092-100_1991.JPG', '2020-04-13 21:54:53', b'1'),
(80, 100, '1586786092-MVIMG_20200215_105930_1.jpg', '2020-04-13 21:54:53', b'1'),
(81, 100, '1586786092-00100lrPORTRAIT_00100_BURST20200215105941635_COVER.jpg', '2020-04-13 21:54:54', b'1'),
(82, 101, '1586949192-starex.jpg', '2020-04-15 19:13:12', b'1'),
(83, 101, '1586949192-v1starex.jpg', '2020-04-15 19:13:13', b'1'),
(84, 103, '1586966723-SAM_0745.JPG', '2020-04-16 00:05:23', b'1'),
(85, 103, '1586966723-lbO17hkK_400x400.jpg', '2020-04-16 00:05:23', b'1');

CREATE TABLE carrental.settings (
  Id int(11) NOT NULL,
  name varchar(255) NOT NULL,
  value text NOT NULL,
  type varchar(20) NOT NULL,
  Is_Active bit(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO carrental.settings (Id, name, value, type, Is_Active) VALUES
(6, 'Driver_Per_Day', '1000', 'system', b'1'),
(7, 'telephone', '+63 917 638 1707', 'contact', b'1'),
(8, 'Email Address', 'inquiry@carrental.com / customer@carrental.com', 'contact', b'1'),
(9, 'Address', 'Poblacion Hagkol Sayre Highway (infront of new bus terminal), Valencia City, Bukidnon 8709', 'contact', b'1'),
(11, 'Mobile phone', '09268406884', 'contact', b'1'),
(15, 'Rental_Pickup_Time', '10:00', 'system', b'1');

CREATE TABLE carrental.status (
  Id int(11) NOT NULL,
  label varchar(50) NOT NULL,
  bootstrap_bg_color varchar(100) NOT NULL,
  Is_Active bit(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO carrental.status (Id, label, bootstrap_bg_color, Is_Active) VALUES
(1, 'Reserved', 'success', b'1'),
(2, 'In Progress', 'danger', b'1'),
(9, 'Returned', 'primary', b'1');

CREATE TABLE carrental.users (
  id int(11) NOT NULL,
  firstname varchar(50) NOT NULL,
  lastname varchar(50) NOT NULL,
  fullname varchar(255) NOT NULL,
  email varchar(150) NOT NULL,
  username varchar(255) NOT NULL,
  password varchar(255) NOT NULL,
  user_type varchar(5) NOT NULL,
  created_at datetime DEFAULT current_timestamp(),
  Is_Active bit(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO carrental.users (id, firstname, lastname, fullname, email, username, password, user_type, created_at, Is_Active) VALUES
(4, 'Enzo', 'Cerbas', 'Enzo Cerbas', 'bvcerbas@up.edu.ph', 'enzo', 'd41d8cd98f00b204e9800998ecf8427e', 'user', '2020-02-01 05:18:35', b'1'),
(12, 'Arvin', 'Reyes', 'Arvin Reyes', 'arvin@gmail.com', 'arvinreyes', '5f4dcc3b5aa765d61d8327deb882cf99', 'admin', '2020-04-14 15:38:23', b'1'),
(13, 'Admin', 'Carrental', 'Admin Carrental', 'johndue@gmail.com', 'admin', '25d55ad283aa400af464c76d713c07ad', 'admin', '2020-04-14 15:45:03', b'1');

ALTER TABLE carrental.cars
  ADD PRIMARY KEY (Id);

ALTER TABLE carrental.clientbookings
  ADD PRIMARY KEY (BookingId);

ALTER TABLE carrental.clientbookingslogs
  ADD PRIMARY KEY (Id);

ALTER TABLE carrental.clientbookingsphotos
  ADD PRIMARY KEY (Id);

ALTER TABLE carrental.clients
  ADD PRIMARY KEY (Id);

ALTER TABLE carrental.clientsphotos
  ADD PRIMARY KEY (Id);

ALTER TABLE carrental.settings
  ADD PRIMARY KEY (Id);

ALTER TABLE carrental.status
  ADD PRIMARY KEY (Id);

ALTER TABLE carrental.users
  ADD PRIMARY KEY (id);

ALTER TABLE carrental.cars
  MODIFY Id int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=52;

ALTER TABLE carrental.clientbookings
  MODIFY BookingId int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=41;

ALTER TABLE carrental.clientbookingslogs
  MODIFY Id int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=12;

ALTER TABLE carrental.clientbookingsphotos
  MODIFY Id int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=23;

ALTER TABLE carrental.clients
  MODIFY Id int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=104;

ALTER TABLE carrental.clientsphotos
  MODIFY Id int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=86;

ALTER TABLE carrental.settings
  MODIFY Id int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=17;

ALTER TABLE carrental.status
  MODIFY Id int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=10;


ALTER TABLE carrental.users
  MODIFY id int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=14;
COMMIT;
EOF
